### ISSUE TITLE
Support Regex for interfaces in VRF

### ISSUE THREAD

**Issue by marcom4rtinez** [network-unit-testing-system/nuts#111]
Sometimes we cannot say which interfaces are assigned to a network instance. E.g. on arista there is an internal vlan automatically assigned or we simply dont want to put all interfaces there from a range. Therefore i think it would be helpful to allow Regex to filter the output.

current:
```yaml
- test_class: TestNapalmNetworkInstances
  test_data:
    - host: fra05-pod1-leaf1
      network_instance: Backbone
      interfaces:
        - Vlan1199
      route_distinguisher: "10.0.253.3:101"
```
desired:
```yaml
- test_class: TestNapalmNetworkInstances
  test_data:
    - host: fra05-pod1-leaf1
      network_instance: Backbone
      interfaces:
        - Vlan\d{4}
      route_distinguisher: "10.0.253.3:101"
```
