### ISSUE TITLE
Improve test class names in test-bundles

### ISSUE THREAD

**Issue by bytinbit** [network-unit-testing-system/nuts#38]
Test classes are defined in yaml bundles like this:
```yaml
- test_class: TestNapalmBgpNeighbors
  test_data:
    - host: R1
      peer: 1.2.3.4
      is_up: false
```

From a usability standpoint it would be good to improve the name of the test class, currently, the backend library is included in the name and could be omitted. Example:

```yaml
- test_class: TestBgpNeighbors
  test_data:
    - host: R1
      peer: 1.2.3.4
      is_up: false
```

Goal: Omit the backend library mentioned in the `test_class` name of a YAML test bundle.

Do not forget to:
- [ ] Update the docs
- [ ] Fix names in `index.py`
